-
  name: Verifying disk usage on VMs
  hosts: rai.01.enk
  vars:
   ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Accessing VM....
      become: true
      become_user: root
      command: df -ht ext4
      register: dfv

    - debug: msg="{{ dfv.stdout }}"
 
  



  