-
  name: Remote Password Change 
  hosts: rai.05.enk, san.01.enk
  vars:
   ansible_python_interpreter: /usr/bin/python3
   password: Gl0ba1_2021!
  tasks:
    - name: Changing User Password
      become: true
      become_user: root
      user:
        name: opsengip
        update_password: always
        password: "{{ password | password_hash('sha512') }}"


