-
  name: Upgrading Remote VMs
  hosts: rai.05.enk
  vars:
   ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Rebooting, please wait....
      become: true
      become_user: root
      reboot:

    - name: Server is up again! Pinging server......
      ping:  

