-
  name: Perform an unattended upgrade 
  hosts: atl.01.bwt

  vars:
   ansible_python_interpreter: /usr/bin/python3
   
  tasks:
    - name: Performing Security upgrade
      become: true
      become_user: root
      shell: unattended-upgrade -d -v
        



  

       

